import turtle
def grid():
    turtle.speed(10)
    turtle.pensize(4)
    turtle.up()
    turtle.goto(-50, 150)
    turtle.down()
    turtle.goto(-50, -150)
    turtle.up()
    turtle.goto(50, 150)
    turtle.down()
    turtle.goto(50, -150)
    turtle.up()
    turtle.goto(-150, 50)
    turtle.down()
    turtle.goto(150, 50)
    turtle.up()
    turtle.goto(-150, -50)
    turtle.down()
    turtle.goto(150, -50)
def x():
    turtle.pencolor("red")
    turtle.left(45)
    turtle.forward(40)
    turtle.backward(80)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(40)
    turtle.backward(80)
grid()
turtle.up()
turtle.goto(0,0)
turtle.down()
x()
turtle.pencolor("blue")
turtle.circle(5)
turtle.done()